#include "message.pb.h" // include header file generated by protoc compiler
#include <iostream>

int main(int argc, char **argv)
{
    // PERSON is namespace (package PERSON) defined in .proto file, Person is from message & person1 is variable
    PERSON::Person person01;

    const std::string name = "asd";
    int ID = 01;
    const std::string email = "asd@xyz.com";

    // setting name, ID and email fields in Person message
    person01.set_name(name); // or *person01.mutable_name() = name;
    person01.set_id(ID);
    person01.set_email(email); // or *person01.mutable_email() = email;

    // getting name, ID and email fields
    std::cout << "[ INFO ]: \n";
    if (person01.has_name()) // has_name() to check if name is initialized
        std::cout << " Name : " << *person01.mutable_name()
                  << std::endl; // mutable returns the address, so we need to dereference it
    else
        std::cout << " Name is not defined" << std::endl;

    if (person01.has_email())
        std::cout << " Email : " << *person01.mutable_email() << std::endl;

    if (person01.has_id())
        std::cout << " Id : " << person01.id() << std::endl;

    std::cout << "\n----------------------" << std::endl;

    // printing proto message with DebugString().
    std::cout << "[ DEBUG ]: \n" << person01.DebugString() << std::endl;
    return EXIT_SUCCESS;
}
